# Generated by Django 3.1.7 on 2021-03-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210331_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
