# Generated by Django 3.1.7 on 2021-04-02 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20210331_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
